-- ═══════════════════════════════════════════════════════════
-- SEED 09: Lengkapi candidate_skills + cv_url SEMUA kandidat
--   PART A : skill baru untuk seed 06 yang masih kosong
--   PART B : skill baru untuk 85 kandidat seed 07 yang kosong
--   PART C : UPDATE cv_url semua candidate_skills yang NULL
-- ═══════════════════════════════════════════════════════════

-- ── PART A — Seed 06: 24 skill baru ──────────────────────
INSERT INTO candidate_skills
  (recruitment_id,pendidikan,jurusan,pengalaman_thn,
   pengalaman_desc,skills,catatan_hr,cv_url)
SELECT r.id, v.pendidikan, v.jurusan, v.exp_thn::INT,
       v.exp_desc, v.skills::JSONB, v.catatan_hr, v.cv_url
FROM recruitment r
JOIN (VALUES
  ('Andi Reski Ramadhani','Staff Frontliner','SMA','IPA',2,'Pernah magang di perusahaan sejenis.','[{"skill": "Komunikasi", "level": 7}, {"skill": "Pelayanan Pelanggan", "level": 8}, {"skill": "Ketelitian", "level": 8}, {"skill": "Kerja Tim", "level": 8}]','Skill masih perlu diasah, namun menunjukkan kemauan belajar tinggi.','https://drive.google.com/open?id=635e3d5b158c12c7ae72785ed0b6'),
  ('Yuliana Putri','Staff Frontliner','SMA','Administrasi Perkantoran',2,'Fresh graduate dengan pengalaman magang 3-6 bulan.','[{"skill": "Komunikasi", "level": 8}, {"skill": "Kasir / POS System", "level": 6}, {"skill": "Kerja Tim", "level": 5}, {"skill": "Ketelitian", "level": 8}, {"skill": "Pelayanan Pelanggan", "level": 6}]','Dokumen tidak lengkap saat pengumpulan berkas. Perlu dilengkapi.','https://drive.google.com/open?id=7c936ad108509779ca5bd1f200db'),
  ('Sitti Nurfadillah','Staff Frontliner','SMA','Administrasi Perkantoran',0,'Pernah kerja part-time di bidang terkait.','[{"skill": "Pelayanan Pelanggan", "level": 6}, {"skill": "Ketelitian", "level": 3}, {"skill": "Komunikasi", "level": 6}]','Skill masih perlu diasah, namun menunjukkan kemauan belajar tinggi.','https://drive.google.com/open?id=c955013713c622e12785ef807071'),
  ('Mardiyanti','Staff Frontliner','SMA','IPA',1,'Memiliki pengalaman di industri yang berkaitan.','[{"skill": "Pelayanan Pelanggan", "level": 5}, {"skill": "Kerja Tim", "level": 7}, {"skill": "Ketelitian", "level": 5}]','Menguasai tools yang dibutuhkan. Cocok untuk tim dinamis.','https://drive.google.com/open?id=58ec2cd30053ad3103d5c36c25d6'),
  ('Rezky Amaliah Putri','Staff Frontliner','SMK','Tata Boga',2,'Berpengalaman di posisi sejenis selama beberapa tahun.','[{"skill": "Komunikasi", "level": 5}, {"skill": "Ketelitian", "level": 7}, {"skill": "Kasir / POS System", "level": 7}, {"skill": "Kerja Tim", "level": 7}, {"skill": "Pelayanan Pelanggan", "level": 7}]','Pengalaman relevan dan sesuai kebutuhan posisi. Skills teknis memadai.','https://drive.google.com/open?id=b2a10f0c0fc94f4d8714b262b7e8'),
  ('Nurhikmah','Staff Frontliner','SMA','Administrasi Perkantoran',1,'Pernah magang di perusahaan sejenis.','[{"skill": "Komunikasi", "level": 4}, {"skill": "Ketelitian", "level": 6}, {"skill": "Pelayanan Pelanggan", "level": 5}, {"skill": "Kasir / POS System", "level": 7}]','Pengalaman di bidang lain, namun transferable skill cukup relevan.','https://drive.google.com/open?id=0d37f468b777b766221f025a9cb1'),
  ('Fitriani Harun','Staff Frontliner','SMA','Tata Niaga',0,'Baru lulus, belum pernah bekerja formal.','[{"skill": "Kasir / POS System", "level": 7}, {"skill": "Ketelitian", "level": 5}, {"skill": "Pelayanan Pelanggan", "level": 5}]','Pengalaman di bidang lain, namun transferable skill cukup relevan.','https://drive.google.com/open?id=0d0e607294380e85be29b5c71d20'),
  ('Muh Rizal Saputra','Staff Frontliner (Shift Malam)','SMA','Tata Niaga',2,'Pengalaman di UMKM lokal Maros selama beberapa tahun.','[{"skill": "Kasir / POS System", "level": 6}, {"skill": "Ketahanan Fisik", "level": 6}, {"skill": "Komunikasi", "level": 7}, {"skill": "Disiplin", "level": 8}]','Kandidat potensial, attitude baik dan komunikatif. Direkomendasikan untuk tahap berikutnya.','https://drive.google.com/open?id=d4838ea762fcd5b20f8edf6ffbfc'),
  ('Herlina Sari','Staff Frontliner (Shift Malam)','SMA','IPS',2,'Fresh graduate dengan pengalaman magang 3-6 bulan.','[{"skill": "Disiplin", "level": 8}, {"skill": "Kasir / POS System", "level": 6}, {"skill": "Komunikasi", "level": 8}]','Masih fresh graduate, butuh onboarding dan training intensif.','https://drive.google.com/open?id=251e8c3de01d86bb781255cbf411'),
  ('Andi Rezki Islamiyah','Captain Store Bantimurung','SMA','IPS',3,'Fresh graduate dengan pengalaman magang 3-6 bulan.','[{"skill": "Manajemen Stok", "level": 9}, {"skill": "Pelayanan Pelanggan", "level": 6}, {"skill": "Pengelolaan Kasir", "level": 8}, {"skill": "Komunikasi", "level": 9}, {"skill": "Leadership", "level": 8}]','Masih fresh graduate, butuh onboarding dan training intensif.','https://drive.google.com/open?id=0c28a79579ad68c200c51a742ea4'),
  ('Baharuddin','Staff Produksi','SMA','Administrasi Perkantoran',1,'Pernah bekerja di bidang yang relevan sebelumnya.','[{"skill": "Ketelitian", "level": 5}, {"skill": "Fisik Prima", "level": 4}, {"skill": "SOP Produksi", "level": 4}]','Menguasai tools yang dibutuhkan. Cocok untuk tim dinamis.','https://drive.google.com/open?id=948b376dfeb58b471088ca32a54d'),
  ('Irfan Maulana','Staff Produksi','SMA','Tata Niaga',2,'Pernah kerja part-time di bidang terkait.','[{"skill": "Kerja Tim", "level": 6}, {"skill": "Ketelitian", "level": 5}, {"skill": "Kebersihan Produksi", "level": 8}, {"skill": "SOP Produksi", "level": 5}, {"skill": "Fisik Prima", "level": 5}]','Masih fresh graduate, butuh onboarding dan training intensif.','https://drive.google.com/open?id=800a9c45bfb222993794a0589a7a'),
  ('Hasrul','Staff Produksi','SMA','IPS',1,'Pernah kerja part-time di bidang terkait.','[{"skill": "Fisik Prima", "level": 6}, {"skill": "Kerja Tim", "level": 4}, {"skill": "Ketelitian", "level": 7}, {"skill": "SOP Produksi", "level": 7}, {"skill": "Kebersihan Produksi", "level": 4}]','Pengalaman relevan dan sesuai kebutuhan posisi. Skills teknis memadai.','https://drive.google.com/open?id=5df98f4afc3ab67c9132e3e101fb'),
  ('Mustafa','Staff Produksi','SMA','IPS',2,'Fresh graduate dengan pengalaman magang 3-6 bulan.','[{"skill": "Ketelitian", "level": 5}, {"skill": "Kerja Tim", "level": 8}, {"skill": "Kebersihan Produksi", "level": 8}, {"skill": "SOP Produksi", "level": 7}, {"skill": "Fisik Prima", "level": 5}]','Menguasai tools yang dibutuhkan. Cocok untuk tim dinamis.','https://drive.google.com/open?id=c3517d4eb28f89c59e98cab3de41'),
  ('Akbar Tanjung','Staff Produksi','SMA','IPA',1,'Pengalaman di UMKM lokal Maros selama beberapa tahun.','[{"skill": "Ketelitian", "level": 4}, {"skill": "Kerja Tim", "level": 4}, {"skill": "Fisik Prima", "level": 4}, {"skill": "Kebersihan Produksi", "level": 4}]','Perlu verifikasi lanjutan terkait pengalaman kerja sebelumnya.','https://drive.google.com/open?id=f2e215600e803b6e5a6e6770e69c'),
  ('Andi Fitria Sari','Design Graphic','D3','Ilmu Komunikasi',2,'Pernah kerja part-time di bidang terkait.','[{"skill": "Desain Packaging", "level": 5}, {"skill": "Konten Sosial Media", "level": 6}, {"skill": "Canva", "level": 6}]','Pengalaman di bidang lain, namun transferable skill cukup relevan.','https://drive.google.com/open?id=e82e4b882d0a12fcf782063db81d'),
  ('Muh Fadli Hidayat','Design Graphic','D3','Teknik Informatika',0,'Pernah kerja part-time di bidang terkait.','[{"skill": "Canva", "level": 7}, {"skill": "Konten Sosial Media", "level": 5}, {"skill": "Desain Packaging", "level": 5}]','Menguasai tools yang dibutuhkan. Cocok untuk tim dinamis.','https://drive.google.com/open?id=36ba5ad487f38e34d1048588c9e0'),
  ('Dimas Eka Pratama','Content Creator','SMA','Tata Niaga',2,'Pengalaman di UMKM lokal Maros selama beberapa tahun.','[{"skill": "Copywriting", "level": 5}, {"skill": "Instagram / TikTok", "level": 5}, {"skill": "Videografi", "level": 6}, {"skill": "Video Editing", "level": 7}, {"skill": "Fotografi", "level": 5}]','Masih fresh graduate, butuh onboarding dan training intensif.','https://drive.google.com/open?id=fb036e6885c02d904b8d2b24bc24'),
  ('Muh. Nawir','Office Boy','SMA','IPA',3,'Pernah kerja part-time di bidang terkait.','[{"skill": "Disiplin", "level": 7}, {"skill": "Kebersihan & Kerapian", "level": 6}, {"skill": "Kerja Tim", "level": 6}]','Kandidat potensial, attitude baik dan komunikatif. Direkomendasikan untuk tahap berikutnya.','https://drive.google.com/open?id=ff387467e4b56c38258922cd3de9'),
  ('Muh. Nasrullah','Driver','SMA','Administrasi Perkantoran',2,'Pernah bekerja di bidang yang relevan sebelumnya.','[{"skill": "Navigasi Daerah Maros", "level": 7}, {"skill": "Disiplin", "level": 8}, {"skill": "Mengemudi", "level": 7}, {"skill": "Tanggung Jawab", "level": 5}]','Skill masih perlu diasah, namun menunjukkan kemauan belajar tinggi.','https://drive.google.com/open?id=785dfcf3bd0921c2183c22aa3bec'),
  ('Nurfadilah Amir','Staff HRD','S1','Psikologi',1,'Fresh graduate dengan pengalaman magang 3-6 bulan.','[{"skill": "Microsoft Excel", "level": 4}, {"skill": "HRIS", "level": 7}, {"skill": "Administrasi HR", "level": 6}]','Perlu tes kemampuan teknis lanjutan sebelum keputusan final.','https://drive.google.com/open?id=d7f1ebcd5c5e1a3f548e6377fc4d'),
  ('Risma Wulandari','Staff HRD','S1','Ekonomi',1,'Pengalaman di UMKM lokal Maros selama beberapa tahun.','[{"skill": "Microsoft Excel", "level": 4}, {"skill": "HRIS", "level": 6}, {"skill": "Administrasi HR", "level": 4}, {"skill": "Rekrutmen", "level": 4}]','Dokumen tidak lengkap saat pengumpulan berkas. Perlu dilengkapi.','https://drive.google.com/open?id=1f96c1b3fdb7175b609c343dd1fb'),
  ('Andi Syarifah Nabila','Staff Accounting','S1','Hukum',1,'Pernah magang di perusahaan sejenis.','[{"skill": "Ketelitian", "level": 7}, {"skill": "Laporan Keuangan", "level": 6}, {"skill": "Akuntansi Dasar", "level": 6}, {"skill": "Microsoft Excel", "level": 7}]','Kandidat potensial, attitude baik dan komunikatif. Direkomendasikan untuk tahap berikutnya.','https://drive.google.com/open?id=0a9f0e260403b9ebd9797c45bab0'),
  ('Nurul Azizah Ramli','Social Media Specialist','S1','Manajemen',3,'Pernah kerja part-time di bidang terkait.','[{"skill": "Instagram Marketing", "level": 8}, {"skill": "Analitik Media Sosial", "level": 7}, {"skill": "Copywriting", "level": 8}, {"skill": "Konten Kreatif", "level": 8}]','Sangat antusias. Motivasi tinggi untuk berkembang di perusahaan.','https://drive.google.com/open?id=b96ae1168eede0df53d43b9c73e1')
) AS v(nama,posisi,pendidikan,jurusan,exp_thn,exp_desc,skills,catatan_hr,cv_url)
  ON r.nama = v.nama AND r.posisi = v.posisi
ON CONFLICT (recruitment_id) DO NOTHING;


-- ── PART B — Seed 07: 85 skill baru ──────────────────────
INSERT INTO candidate_skills
  (recruitment_id,pendidikan,jurusan,pengalaman_thn,
   pengalaman_desc,skills,catatan_hr,cv_url)
SELECT r.id, v.pendidikan, v.jurusan, v.exp_thn::INT,
       v.exp_desc, v.skills::JSONB, v.catatan_hr, v.cv_url
FROM recruitment r
JOIN (VALUES
  ('Amelia Wira','Captain Store','SMK','Administrasi Perkantoran',1,'Pernah kerja part-time di bidang terkait.','[{"skill": "Leadership", "level": 7}, {"skill": "Manajemen Stok", "level": 6}, {"skill": "Pelayanan Pelanggan", "level": 6}, {"skill": "Pelaporan Operasional", "level": 7}, {"skill": "Pengelolaan Kasir", "level": 7}]','Masih fresh graduate, butuh onboarding dan training intensif.','https://drive.google.com/open?id=4ebda7ba31a8645e7563dce4dfe8'),
  ('Suci Salam','Captain Store','SMA','Tata Niaga',4,'Pengalaman di UMKM lokal Maros selama beberapa tahun.','[{"skill": "Pengelolaan Kasir", "level": 9}, {"skill": "Leadership", "level": 6}, {"skill": "Pelaporan Operasional", "level": 9}, {"skill": "Pelayanan Pelanggan", "level": 8}, {"skill": "Manajemen Stok", "level": 9}]','Perlu tes kemampuan teknis lanjutan sebelum keputusan final.','https://drive.google.com/open?id=b3818b058133ee31c47211687613'),
  ('Andi Fitria Wahab','Supervisor Produksi','D3','Administrasi Bisnis',3,'Baru lulus, belum pernah bekerja formal.','[{"skill": "SOP Produksi", "level": 6}, {"skill": "Leadership", "level": 7}, {"skill": "Manajemen Produksi", "level": 8}]','Sudah pernah kerja di industri serupa. Onboarding bisa lebih cepat.','https://drive.google.com/open?id=344c35da43389016e53c9dd252d4'),
  ('Wulandari Wahid','Social Media Specialist','S1','Ilmu Komunikasi',2,'Baru lulus, belum pernah bekerja formal.','[{"skill": "Konten Kreatif", "level": 7}, {"skill": "Analitik Media Sosial", "level": 7}, {"skill": "Copywriting", "level": 5}, {"skill": "Instagram Marketing", "level": 7}, {"skill": "Facebook Ads", "level": 6}]','Skill masih perlu diasah, namun menunjukkan kemauan belajar tinggi.','https://drive.google.com/open?id=61479cc6749c5a5613fd5ffc7e17'),
  ('Wahyu Kurnia','Staff Frontliner (Shift Malam)','SMA','Tata Niaga',0,'Baru lulus, belum pernah bekerja formal.','[{"skill": "Kasir / POS System", "level": 5}, {"skill": "Pelayanan Pelanggan", "level": 6}, {"skill": "Komunikasi", "level": 8}, {"skill": "Ketahanan Fisik", "level": 7}, {"skill": "Disiplin", "level": 6}]','Menguasai tools yang dibutuhkan. Cocok untuk tim dinamis.','https://drive.google.com/open?id=9c5cfcb7cdd2b2980c6114b84a36'),
  ('Intan Patta','Marketing Executive','S1','Ilmu Komunikasi',2,'Pernah magang di perusahaan sejenis.','[{"skill": "Microsoft Excel", "level": 8}, {"skill": "Digital Marketing", "level": 5}, {"skill": "Analisis Pasar", "level": 6}, {"skill": "Presentasi", "level": 7}, {"skill": "Komunikasi", "level": 8}]','Sudah pernah kerja di industri serupa. Onboarding bisa lebih cepat.','https://drive.google.com/open?id=9b2381a03f30c708d9eded558ae9'),
  ('Mutia Maulana','Staff HRD','S1','Manajemen',3,'Baru lulus, belum pernah bekerja formal.','[{"skill": "Microsoft Excel", "level": 8}, {"skill": "HRIS", "level": 6}, {"skill": "Rekrutmen", "level": 7}]','Domisili dalam Maros, tidak ada masalah jarak. Bersedia bekerja fleksibel.','https://drive.google.com/open?id=dbb233b3cad1898dcb599789ee10'),
  ('Herlina Bahri','Office Boy','SMA','IPS',3,'Pernah kerja part-time di bidang terkait.','[{"skill": "Pengiriman Dokumen", "level": 7}, {"skill": "Kebersihan & Kerapian", "level": 6}, {"skill": "Disiplin", "level": 7}, {"skill": "Tanggung Jawab", "level": 8}, {"skill": "Kerja Tim", "level": 7}]','Pengalaman di bidang lain, namun transferable skill cukup relevan.','https://drive.google.com/open?id=9b58d80652450a19788a023d81f0'),
  ('Reski Wahyuni','Staff HRD','S1','Manajemen',3,'Pernah kerja part-time di bidang terkait.','[{"skill": "Administrasi HR", "level": 6}, {"skill": "HRIS", "level": 6}, {"skill": "Komunikasi", "level": 9}]','Domisili dalam Maros, tidak ada masalah jarak. Bersedia bekerja fleksibel.','https://drive.google.com/open?id=5329769e531b7977c5c9438a396e'),
  ('Yanti Naim','Staff Frontliner','SMA','IPA',0,'Fresh graduate dengan pengalaman magang 3-6 bulan.','[{"skill": "Kerja Tim", "level": 5}, {"skill": "Komunikasi", "level": 6}, {"skill": "Kasir / POS System", "level": 5}]','Dokumen tidak lengkap saat pengumpulan berkas. Perlu dilengkapi.','https://drive.google.com/open?id=3da4f27fec093907a6bdd47b0fdb'),
  ('Reski Natsir','Design Graphic','D3','Akuntansi',2,'Berpengalaman di posisi sejenis selama beberapa tahun.','[{"skill": "Canva", "level": 7}, {"skill": "Adobe Photoshop", "level": 8}, {"skill": "Adobe Illustrator", "level": 6}, {"skill": "Konten Sosial Media", "level": 8}]','Masih fresh graduate, butuh onboarding dan training intensif.','https://drive.google.com/open?id=3776b6f6d33eca098c7d3bf8af18'),
  ('Valdi Nai Patta','Design Graphic','D3','Manajemen',2,'Fresh graduate dengan pengalaman magang 3-6 bulan.','[{"skill": "Desain Packaging", "level": 6}, {"skill": "Konten Sosial Media", "level": 7}, {"skill": "Adobe Photoshop", "level": 8}]','Menguasai tools yang dibutuhkan. Cocok untuk tim dinamis.','https://drive.google.com/open?id=caf70be1364eac04e4b38c2a1056'),
  ('Dewi Kalla','Staff Frontliner','SMA','IPS',0,'Fresh graduate dengan pengalaman magang 3-6 bulan.','[{"skill": "Komunikasi", "level": 4}, {"skill": "Ketelitian", "level": 4}, {"skill": "Pelayanan Pelanggan", "level": 8}, {"skill": "Kasir / POS System", "level": 7}]','Sudah pernah kerja di industri serupa. Onboarding bisa lebih cepat.','https://drive.google.com/open?id=6c4dfe73bd45a8b37c2d949065b2'),
  ('Rani Hamzah','Business Development Executive','S1','Psikologi',2,'Memiliki pengalaman di industri yang berkaitan.','[{"skill": "Komunikasi", "level": 6}, {"skill": "Negosiasi", "level": 6}, {"skill": "Presentasi", "level": 8}, {"skill": "Microsoft Excel", "level": 7}]','Skill masih perlu diasah, namun menunjukkan kemauan belajar tinggi.','https://drive.google.com/open?id=dfaef897e198eb86d7163c76cefd'),
  ('Udin Naim','Staff Purchasing','D3','Ilmu Komunikasi',1,'Pengalaman di UMKM lokal Maros selama beberapa tahun.','[{"skill": "Negosiasi Harga", "level": 4}, {"skill": "Administrasi", "level": 5}, {"skill": "Microsoft Excel", "level": 6}]','Kandidat potensial, attitude baik dan komunikatif. Direkomendasikan untuk tahap berikutnya.','https://drive.google.com/open?id=4f40c8f28c1aa51e07178dbf19b6'),
  ('Mansyur Salam','Content Creator','SMA','Tata Niaga',1,'Pernah magang di perusahaan sejenis.','[{"skill": "Copywriting", "level": 4}, {"skill": "Videografi", "level": 7}, {"skill": "Video Editing", "level": 4}]','Dokumen tidak lengkap saat pengumpulan berkas. Perlu dilengkapi.','https://drive.google.com/open?id=8045eca5df44af3ec029e33ce428'),
  ('Wahyu Basri Unru','Supervisor Produksi','D3','Ilmu Komunikasi',3,'Pengalaman di UMKM lokal Maros selama beberapa tahun.','[{"skill": "Leadership", "level": 6}, {"skill": "Ketelitian", "level": 7}, {"skill": "SOP Produksi", "level": 8}, {"skill": "Manajemen Produksi", "level": 6}]','Dokumen tidak lengkap saat pengumpulan berkas. Perlu dilengkapi.','https://drive.google.com/open?id=c8b14552e17741788e3a588b63d1'),
  ('Qadri Pratama Latif','Supervisor Store Tambua','SMA','Administrasi Perkantoran',2,'Pernah magang di perusahaan sejenis.','[{"skill": "Pelaporan Operasional", "level": 6}, {"skill": "Leadership", "level": 6}, {"skill": "Pengelolaan Outlet", "level": 7}, {"skill": "Manajemen Tim", "level": 6}, {"skill": "Pelayanan Pelanggan", "level": 8}]','Menguasai tools yang dibutuhkan. Cocok untuk tim dinamis.','https://drive.google.com/open?id=7e26d8dadb6ee0952f528a2eba83'),
  ('Arif Hadi Ramadhan','Social Media Specialist','S1','Ilmu Komunikasi',2,'Pernah bekerja di bidang yang relevan sebelumnya.','[{"skill": "Konten Kreatif", "level": 7}, {"skill": "Copywriting", "level": 7}, {"skill": "Facebook Ads", "level": 6}, {"skill": "Instagram Marketing", "level": 7}, {"skill": "Analitik Media Sosial", "level": 8}]','Perlu verifikasi lanjutan terkait pengalaman kerja sebelumnya.','https://drive.google.com/open?id=27bf4a70d998171fd47db408ecd9'),
  ('Nurul Latif','Sales Executive','SMA','IPA',1,'Baru lulus, belum pernah bekerja formal.','[{"skill": "Presentasi", "level": 6}, {"skill": "Target Sales", "level": 5}, {"skill": "Negosiasi", "level": 5}, {"skill": "Jaringan Relasi", "level": 7}, {"skill": "Komunikasi", "level": 4}]','Kandidat potensial, attitude baik dan komunikatif. Direkomendasikan untuk tahap berikutnya.','https://drive.google.com/open?id=32fff8f2615f2d8ddad99e7acb7e'),
  ('Mardiyanti Sabang','Staff Produksi','SMA','IPA',2,'Fresh graduate dengan pengalaman magang 3-6 bulan.','[{"skill": "Kerja Tim", "level": 7}, {"skill": "Fisik Prima", "level": 8}, {"skill": "Ketelitian", "level": 6}]','Masih fresh graduate, butuh onboarding dan training intensif.','https://drive.google.com/open?id=87b6b1759933049d7710eafdb806'),
  ('Vira Vahid','Captain Store Batas Kota','SMA','IPA',3,'Pernah magang di perusahaan sejenis.','[{"skill": "Manajemen Stok", "level": 7}, {"skill": "Pelayanan Pelanggan", "level": 7}, {"skill": "Pengelolaan Kasir", "level": 7}, {"skill": "Pelaporan Operasional", "level": 8}]','Kandidat potensial, attitude baik dan komunikatif. Direkomendasikan untuk tahap berikutnya.','https://drive.google.com/open?id=0c82ff73cfeca8a9390b81b4858d'),
  ('Rahma Zainab','Supervisor Store Batas Kota','SMK','Administrasi Perkantoran',5,'Pernah kerja part-time di bidang terkait.','[{"skill": "Manajemen Tim", "level": 7}, {"skill": "Pelayanan Pelanggan", "level": 6}, {"skill": "Pelaporan Operasional", "level": 6}]','Skill masih perlu diasah, namun menunjukkan kemauan belajar tinggi.','https://drive.google.com/open?id=8e5474f41d62ca878eb798a07334'),
  ('Suci Basri','Staff HRD','S1','Psikologi',0,'Memiliki pengalaman di industri yang berkaitan.','[{"skill": "Administrasi HR", "level": 4}, {"skill": "Microsoft Excel", "level": 6}, {"skill": "Rekrutmen", "level": 4}, {"skill": "HRIS", "level": 6}]','Domisili dalam Maros, tidak ada masalah jarak. Bersedia bekerja fleksibel.','https://drive.google.com/open?id=46323464cf9956dc0efdc1f37422'),
  ('Rani Basri','Captain Frontliner','SMA','IPS',1,'Pernah magang di perusahaan sejenis.','[{"skill": "Kasir / POS System", "level": 5}, {"skill": "Pelayanan Pelanggan", "level": 7}, {"skill": "Komunikasi", "level": 5}, {"skill": "Leadership", "level": 6}]','Pengalaman relevan dan sesuai kebutuhan posisi. Skills teknis memadai.','https://drive.google.com/open?id=46bd7fefc751f68b77b2f81785ea'),
  ('Salma Karim','Staff QC','SMK','TKJ',0,'Berpengalaman di posisi sejenis selama beberapa tahun.','[{"skill": "Dokumentasi QC", "level": 6}, {"skill": "Pengujian Produk", "level": 5}, {"skill": "Ketelitian", "level": 4}]','Pengalaman relevan dan sesuai kebutuhan posisi. Skills teknis memadai.','https://drive.google.com/open?id=3ea0783a04393cfab1f501ad9326'),
  ('Fitriani Daeng','Captain Store','SMA','IPA',4,'Baru lulus, belum pernah bekerja formal.','[{"skill": "Pelayanan Pelanggan", "level": 9}, {"skill": "Pelaporan Operasional", "level": 7}, {"skill": "Leadership", "level": 9}, {"skill": "Manajemen Stok", "level": 9}, {"skill": "Pengelolaan Kasir", "level": 6}]','Skill masih perlu diasah, namun menunjukkan kemauan belajar tinggi.','https://drive.google.com/open?id=706be2d94938da3d188fde82bfc1'),
  ('Valdi Kurnia Idrus','Design Graphic','D3','Akuntansi',0,'Baru lulus, belum pernah bekerja formal.','[{"skill": "Konten Sosial Media", "level": 4}, {"skill": "Adobe Illustrator", "level": 5}, {"skill": "Canva", "level": 5}]','Menguasai tools yang dibutuhkan. Cocok untuk tim dinamis.','https://drive.google.com/open?id=511fa0b05a4e31d5e27244d1fd75'),
  ('Alamsyah Talib','Manager Operasional','S1','Hukum',8,'Memiliki pengalaman di industri yang berkaitan.','[{"skill": "Leadership", "level": 7}, {"skill": "KPI", "level": 7}, {"skill": "Komunikasi", "level": 7}, {"skill": "Analisis Proses", "level": 9}, {"skill": "Manajemen Operasional", "level": 9}]','Dokumen tidak lengkap saat pengumpulan berkas. Perlu dilengkapi.','https://drive.google.com/open?id=2d25b0c4a504f731c57ff1228ac8'),
  ('Rani Jalil','Sales Executive','SMA','Tata Niaga',4,'Pernah magang di perusahaan sejenis.','[{"skill": "Jaringan Relasi", "level": 9}, {"skill": "Target Sales", "level": 6}, {"skill": "Negosiasi", "level": 9}]','Perlu verifikasi lanjutan terkait pengalaman kerja sebelumnya.','https://drive.google.com/open?id=a45a20b7cddf401a35c9d71083c0'),
  ('Qori Jaya','Staff Frontliner (Shift Malam)','SMA','IPS',2,'Memiliki pengalaman di industri yang berkaitan.','[{"skill": "Kasir / POS System", "level": 7}, {"skill": "Ketahanan Fisik", "level": 5}, {"skill": "Disiplin", "level": 6}]','Pengalaman relevan dan sesuai kebutuhan posisi. Skills teknis memadai.','https://drive.google.com/open?id=a98c644744c07ad5929b5918ba81'),
  ('Akbar Jaya','Business Development Executive','S1','Manajemen',3,'Pengalaman di UMKM lokal Maros selama beberapa tahun.','[{"skill": "Analisis Pasar", "level": 7}, {"skill": "Microsoft Excel", "level": 9}, {"skill": "Komunikasi", "level": 6}, {"skill": "Presentasi", "level": 7}, {"skill": "Negosiasi", "level": 7}]','Pengalaman di bidang lain, namun transferable skill cukup relevan.','https://drive.google.com/open?id=c9b96a3399c0ee1ed12531f6f7fe'),
  ('Sitti Pratama','Design Graphic','D3','Manajemen',0,'Pengalaman di UMKM lokal Maros selama beberapa tahun.','[{"skill": "Canva", "level": 5}, {"skill": "Konten Sosial Media", "level": 4}, {"skill": "Adobe Illustrator", "level": 5}, {"skill": "Adobe Photoshop", "level": 5}]','Kandidat potensial, attitude baik dan komunikatif. Direkomendasikan untuk tahap berikutnya.','https://drive.google.com/open?id=6c9ee093ec40638365207c236f45'),
  ('Ruslan Lestari','Supervisor Supply Chain Management','S1','Ekonomi',3,'Pernah kerja part-time di bidang terkait.','[{"skill": "Supply Chain", "level": 7}, {"skill": "Manajemen Inventori", "level": 9}, {"skill": "Analisis Stok", "level": 9}, {"skill": "Negosiasi Vendor", "level": 7}]','Kandidat potensial, attitude baik dan komunikatif. Direkomendasikan untuk tahap berikutnya.','https://drive.google.com/open?id=a5fd612ff9bc998a21b2e43ab41d'),
  ('Hasrul Rauf','Marketing Executive','S1','Psikologi',1,'Pernah kerja part-time di bidang terkait.','[{"skill": "Komunikasi", "level": 7}, {"skill": "Microsoft Excel", "level": 7}, {"skill": "Presentasi", "level": 4}]','Sudah pernah kerja di industri serupa. Onboarding bisa lebih cepat.','https://drive.google.com/open?id=36c0d7848ecd08bfa3a460fd8779'),
  ('Andi Fitria Ansar','Staff QC','SMK','Administrasi Perkantoran',2,'Baru lulus, belum pernah bekerja formal.','[{"skill": "Ketelitian", "level": 7}, {"skill": "SOP Produksi", "level": 5}, {"skill": "Quality Control", "level": 8}, {"skill": "Dokumentasi QC", "level": 7}, {"skill": "Pengujian Produk", "level": 6}]','Perlu verifikasi lanjutan terkait pengalaman kerja sebelumnya.','https://drive.google.com/open?id=a41511b6da6294b6f4716cdaefd8'),
  ('Pandu Idrus','Sales Executive','SMA','IPS',3,'Berpengalaman di posisi sejenis selama beberapa tahun.','[{"skill": "Jaringan Relasi", "level": 7}, {"skill": "Negosiasi", "level": 6}, {"skill": "Presentasi", "level": 6}, {"skill": "Target Sales", "level": 8}]','Kandidat potensial, attitude baik dan komunikatif. Direkomendasikan untuk tahap berikutnya.','https://drive.google.com/open?id=8a409e6019bd48db812aa3796631'),
  ('Ilham Idrus','Staff QC','SMK','Teknik Mesin',3,'Pernah bekerja di bidang yang relevan sebelumnya.','[{"skill": "Pengujian Produk", "level": 8}, {"skill": "Quality Control", "level": 9}, {"skill": "SOP Produksi", "level": 6}]','Pengalaman relevan dan sesuai kebutuhan posisi. Skills teknis memadai.','https://drive.google.com/open?id=76159d8cbc2ae720c2b6bc1491bd'),
  ('Muh. Eko Unru','Captain Store','SMA','Administrasi Perkantoran',2,'Berpengalaman di posisi sejenis selama beberapa tahun.','[{"skill": "Manajemen Stok", "level": 7}, {"skill": "Pelayanan Pelanggan", "level": 6}, {"skill": "Leadership", "level": 7}, {"skill": "Pengelolaan Kasir", "level": 7}, {"skill": "Pelaporan Operasional", "level": 7}]','Pengalaman di bidang lain, namun transferable skill cukup relevan.','https://drive.google.com/open?id=a4332c1ec9a867ca0acf0d857a8d'),
  ('Alamsyah Verdi','Design Graphic','D3','Administrasi Bisnis',3,'Memiliki pengalaman di industri yang berkaitan.','[{"skill": "Konten Sosial Media", "level": 7}, {"skill": "Canva", "level": 9}, {"skill": "Desain Packaging", "level": 9}, {"skill": "Adobe Illustrator", "level": 6}]','Masih fresh graduate, butuh onboarding dan training intensif.','https://drive.google.com/open?id=f2c924010cfa205a216ac13cb3c3'),
  ('Hasrul Wahid','Supervisor Supply Chain Management','S1','Psikologi',3,'Pernah magang di perusahaan sejenis.','[{"skill": "Analisis Stok", "level": 9}, {"skill": "Supply Chain", "level": 8}, {"skill": "Negosiasi Vendor", "level": 8}, {"skill": "Manajemen Inventori", "level": 9}, {"skill": "Microsoft Excel", "level": 9}]','Sudah pernah kerja di industri serupa. Onboarding bisa lebih cepat.','https://drive.google.com/open?id=2b07f11c5643d8c19fa91b8cc025'),
  ('Edi Dwi Mahmud','Supervisor Store Tambua','SMK','Tata Niaga',3,'Berpengalaman di posisi sejenis selama beberapa tahun.','[{"skill": "Pelaporan Operasional", "level": 6}, {"skill": "Leadership", "level": 8}, {"skill": "Manajemen Tim", "level": 6}, {"skill": "Pengelolaan Outlet", "level": 7}]','Menguasai tools yang dibutuhkan. Cocok untuk tim dinamis.','https://drive.google.com/open?id=aa2cf34b1a3cc57a3727e001bff7'),
  ('Qori Karim','Supervisor Supply Chain & Production Control','S1','Ilmu Komunikasi',3,'Pernah magang di perusahaan sejenis.','[{"skill": "Koordinasi", "level": 6}, {"skill": "Manajemen Inventori", "level": 9}, {"skill": "Microsoft Excel", "level": 7}, {"skill": "Supply Chain", "level": 8}]','Pengalaman di bidang lain, namun transferable skill cukup relevan.','https://drive.google.com/open?id=c311dad32d6d33ea7358589f2db7'),
  ('Lina Mappanyompa','Teknisi','SMA','Administrasi Perkantoran',6,'Memiliki pengalaman di industri yang berkaitan.','[{"skill": "Kelistrikan", "level": 6}, {"skill": "Perawatan Mesin", "level": 7}, {"skill": "Perbaikan Peralatan", "level": 9}, {"skill": "Troubleshooting", "level": 7}]','Menguasai tools yang dibutuhkan. Cocok untuk tim dinamis.','https://drive.google.com/open?id=a629102a08a7050c2a1e4f67071e'),
  ('Muh. Maulana Mahmud','Marketing Executive','S1','Ekonomi',4,'Memiliki pengalaman di industri yang berkaitan.','[{"skill": "Microsoft Excel", "level": 7}, {"skill": "Komunikasi", "level": 6}, {"skill": "Presentasi", "level": 7}, {"skill": "Digital Marketing", "level": 6}, {"skill": "Analisis Pasar", "level": 9}]','Perlu verifikasi lanjutan terkait pengalaman kerja sebelumnya.','https://drive.google.com/open?id=1205991a8b701707292b2a22a8be'),
  ('Citra Kalla','Supervisor Store Batas Kota','SMK','Tata Boga',4,'Memiliki pengalaman di industri yang berkaitan.','[{"skill": "Manajemen Tim", "level": 8}, {"skill": "Pengelolaan Outlet", "level": 6}, {"skill": "Pelayanan Pelanggan", "level": 6}, {"skill": "Pelaporan Operasional", "level": 9}]','Sangat antusias. Motivasi tinggi untuk berkembang di perusahaan.','https://drive.google.com/open?id=3ae103e86b2b59b4ee60b1b31b4d'),
  ('Suci Talib','Staff Frontliner','SMA','IPS',1,'Baru lulus, belum pernah bekerja formal.','[{"skill": "Ketelitian", "level": 4}, {"skill": "Komunikasi", "level": 6}, {"skill": "Pelayanan Pelanggan", "level": 4}, {"skill": "Kasir / POS System", "level": 6}]','Domisili dalam Maros, tidak ada masalah jarak. Bersedia bekerja fleksibel.','https://drive.google.com/open?id=8f6d3b5685fa0358588f9a173fb0'),
  ('Indah Rahman','Staff Accounting','D3','DKV',2,'Memiliki pengalaman di industri yang berkaitan.','[{"skill": "Pembukuan", "level": 7}, {"skill": "Laporan Keuangan", "level": 6}, {"skill": "Akuntansi Dasar", "level": 8}, {"skill": "Ketelitian", "level": 7}]','Masih fresh graduate, butuh onboarding dan training intensif.','https://drive.google.com/open?id=268436f6a519aa6329ee7ddfdfc8'),
  ('Yanti Zainab','Captain Frontliner','SMA','Tata Niaga',2,'Berpengalaman di posisi sejenis selama beberapa tahun.','[{"skill": "Leadership", "level": 5}, {"skill": "Komunikasi", "level": 8}, {"skill": "Kasir / POS System", "level": 6}, {"skill": "Manajemen Stok", "level": 8}]','Menguasai tools yang dibutuhkan. Cocok untuk tim dinamis.','https://drive.google.com/open?id=755d36634e29db203d1d7b1d3f6b'),
  ('Fitriani Rahman','Staff Purchasing','D3','Ilmu Komunikasi',2,'Berpengalaman di posisi sejenis selama beberapa tahun.','[{"skill": "Analisis Harga", "level": 6}, {"skill": "Administrasi", "level": 5}, {"skill": "Microsoft Excel", "level": 6}, {"skill": "Manajemen Vendor", "level": 6}, {"skill": "Negosiasi Harga", "level": 7}]','Skill masih perlu diasah, namun menunjukkan kemauan belajar tinggi.','https://drive.google.com/open?id=5511f7670296ae414489ea50236a'),
  ('Lina Basri','Social Media Specialist','S1','Akuntansi',2,'Pernah bekerja di bidang yang relevan sebelumnya.','[{"skill": "Instagram Marketing", "level": 8}, {"skill": "Copywriting", "level": 7}, {"skill": "Konten Kreatif", "level": 5}, {"skill": "Facebook Ads", "level": 5}]','Pengalaman relevan dan sesuai kebutuhan posisi. Skills teknis memadai.','https://drive.google.com/open?id=abcbd0928fdd0119671c984b8437'),
  ('Laode Wira','Business Development Executive','S1','Psikologi',2,'Berpengalaman di posisi sejenis selama beberapa tahun.','[{"skill": "Analisis Pasar", "level": 6}, {"skill": "Presentasi", "level": 7}, {"skill": "Microsoft Excel", "level": 7}]','Skill masih perlu diasah, namun menunjukkan kemauan belajar tinggi.','https://drive.google.com/open?id=7b15ec8f39e66384ee9552f5eb37'),
  ('Arif Jalil','Teknisi','SMK','TKJ',3,'Baru lulus, belum pernah bekerja formal.','[{"skill": "Kelistrikan", "level": 6}, {"skill": "Perbaikan Peralatan", "level": 8}, {"skill": "Mekanik", "level": 9}]','Perlu verifikasi lanjutan terkait pengalaman kerja sebelumnya.','https://drive.google.com/open?id=aebb599f7e28691d092875196d11'),
  ('Wahdah Jalil','Staff Frontliner (Shift Malam)','SMA','Tata Niaga',2,'Pernah bekerja di bidang yang relevan sebelumnya.','[{"skill": "Komunikasi", "level": 8}, {"skill": "Pelayanan Pelanggan", "level": 6}, {"skill": "Ketahanan Fisik", "level": 7}, {"skill": "Disiplin", "level": 7}]','Domisili dalam Maros, tidak ada masalah jarak. Bersedia bekerja fleksibel.','https://drive.google.com/open?id=ab39cb3ea26149f88ed2e5ae7300'),
  ('Nurul Effendi','Staff Frontliner','SMA','Tata Niaga',2,'Memiliki pengalaman di industri yang berkaitan.','[{"skill": "Kerja Tim", "level": 7}, {"skill": "Kasir / POS System", "level": 7}, {"skill": "Ketelitian", "level": 8}, {"skill": "Pelayanan Pelanggan", "level": 7}, {"skill": "Komunikasi", "level": 6}]','Skill masih perlu diasah, namun menunjukkan kemauan belajar tinggi.','https://drive.google.com/open?id=54e43b4f328dcc5e9453a82b3a0f'),
  ('Ulfa Ramadhan','Staff Frontliner (Shift Malam)','SMA','IPA',2,'Pernah magang di perusahaan sejenis.','[{"skill": "Disiplin", "level": 6}, {"skill": "Pelayanan Pelanggan", "level": 8}, {"skill": "Kasir / POS System", "level": 7}, {"skill": "Ketahanan Fisik", "level": 5}]','Menguasai tools yang dibutuhkan. Cocok untuk tim dinamis.','https://drive.google.com/open?id=872faa72ab41c203d54f070227f9'),
  ('Khaerul Wira Rasid','Office Boy','SMA','IPS',1,'Pernah kerja part-time di bidang terkait.','[{"skill": "Kebersihan & Kerapian", "level": 4}, {"skill": "Kerja Tim", "level": 6}, {"skill": "Pengiriman Dokumen", "level": 4}, {"skill": "Tanggung Jawab", "level": 6}, {"skill": "Disiplin", "level": 4}]','Perlu tes kemampuan teknis lanjutan sebelum keputusan final.','https://drive.google.com/open?id=a663b92489eed52397990bc11654'),
  ('Irfan Nai Taba','Captain Store','SMK','Tata Boga',3,'Pengalaman di UMKM lokal Maros selama beberapa tahun.','[{"skill": "Pengelolaan Kasir", "level": 9}, {"skill": "Manajemen Stok", "level": 6}, {"skill": "Pelaporan Operasional", "level": 6}, {"skill": "Leadership", "level": 6}]','Masih fresh graduate, butuh onboarding dan training intensif.','https://drive.google.com/open?id=ee4b644f79a305e1f457ad548951'),
  ('Sitti Umar','Staff Produksi','SMA','IPA',1,'Berpengalaman di posisi sejenis selama beberapa tahun.','[{"skill": "SOP Produksi", "level": 5}, {"skill": "Kerja Tim", "level": 4}, {"skill": "Fisik Prima", "level": 6}, {"skill": "Kebersihan Produksi", "level": 6}, {"skill": "Ketelitian", "level": 4}]','Domisili dalam Maros, tidak ada masalah jarak. Bersedia bekerja fleksibel.','https://drive.google.com/open?id=f42e1741c835df8f651074dfe805'),
  ('Cakra Wira Karim','Captain Store','SMK','Tata Boga',1,'Pernah bekerja di bidang yang relevan sebelumnya.','[{"skill": "Pengelolaan Kasir", "level": 5}, {"skill": "Leadership", "level": 4}, {"skill": "Pelaporan Operasional", "level": 4}, {"skill": "Manajemen Stok", "level": 6}, {"skill": "Pelayanan Pelanggan", "level": 5}]','Domisili dalam Maros, tidak ada masalah jarak. Bersedia bekerja fleksibel.','https://drive.google.com/open?id=0c97532f15448cd133651230f86a'),
  ('Andi Rezki Amir','Staff Frontliner','SMA','IPS',1,'Pengalaman di UMKM lokal Maros selama beberapa tahun.','[{"skill": "Kasir / POS System", "level": 7}, {"skill": "Pelayanan Pelanggan", "level": 5}, {"skill": "Komunikasi", "level": 5}]','Perlu verifikasi lanjutan terkait pengalaman kerja sebelumnya.','https://drive.google.com/open?id=d316a0422a28eaad3a682f93e497'),
  ('Ilham Wira','Manager Operasional','S1','Psikologi',8,'Fresh graduate dengan pengalaman magang 3-6 bulan.','[{"skill": "Leadership", "level": 8}, {"skill": "Komunikasi", "level": 8}, {"skill": "KPI", "level": 7}, {"skill": "Manajemen Operasional", "level": 7}]','Skill masih perlu diasah, namun menunjukkan kemauan belajar tinggi.','https://drive.google.com/open?id=e3f127b21dedea597c092d5dc021'),
  ('Firman Verdi','Marketing Manager','S1','Teknik Industri',8,'Pernah bekerja di bidang yang relevan sebelumnya.','[{"skill": "Manajemen Tim", "level": 7}, {"skill": "Analisis Data", "level": 6}, {"skill": "Negosiasi", "level": 7}]','Sudah pernah kerja di industri serupa. Onboarding bisa lebih cepat.','https://drive.google.com/open?id=1d3ddd77625d96531af638cc460d'),
  ('Veni Hidayat','Supervisor Store Batas Kota','SMK','TKJ',3,'Pengalaman di UMKM lokal Maros selama beberapa tahun.','[{"skill": "Pengelolaan Outlet", "level": 7}, {"skill": "Pelayanan Pelanggan", "level": 9}, {"skill": "Leadership", "level": 9}, {"skill": "Pelaporan Operasional", "level": 7}, {"skill": "Manajemen Tim", "level": 6}]','Pengalaman relevan dan sesuai kebutuhan posisi. Skills teknis memadai.','https://drive.google.com/open?id=37b15400f3baac3a92ff791f9a9b'),
  ('Fitriani Wahab','Marketing Executive','S1','Hukum',1,'Pengalaman di UMKM lokal Maros selama beberapa tahun.','[{"skill": "Digital Marketing", "level": 6}, {"skill": "Analisis Pasar", "level": 5}, {"skill": "Presentasi", "level": 5}, {"skill": "Microsoft Excel", "level": 5}, {"skill": "Komunikasi", "level": 6}]','Dokumen tidak lengkap saat pengumpulan berkas. Perlu dilengkapi.','https://drive.google.com/open?id=c02d9d55aae16a14616631c64332'),
  ('Pratiwi Taba','Teknisi','SMK','Tata Niaga',4,'Pengalaman di UMKM lokal Maros selama beberapa tahun.','[{"skill": "Mekanik", "level": 9}, {"skill": "Perbaikan Peralatan", "level": 8}, {"skill": "Kelistrikan", "level": 6}, {"skill": "Troubleshooting", "level": 9}]','Sangat antusias. Motivasi tinggi untuk berkembang di perusahaan.','https://drive.google.com/open?id=dc6ce959e7bcff2fe0521def34a0'),
  ('Wawan Karim','Driver','SMA','Tata Niaga',6,'Pernah kerja part-time di bidang terkait.','[{"skill": "Perawatan Kendaraan", "level": 9}, {"skill": "Disiplin", "level": 8}, {"skill": "Navigasi Daerah Maros", "level": 7}]','Pengalaman di bidang lain, namun transferable skill cukup relevan.','https://drive.google.com/open?id=0025da771e898ac3ea6bcef02836'),
  ('Gita Salam','Social Media Specialist','S1','Teknik Industri',1,'Pernah bekerja di bidang yang relevan sebelumnya.','[{"skill": "Copywriting", "level": 6}, {"skill": "Instagram Marketing", "level": 5}, {"skill": "Analitik Media Sosial", "level": 4}, {"skill": "Konten Kreatif", "level": 6}, {"skill": "Facebook Ads", "level": 4}]','Sudah pernah kerja di industri serupa. Onboarding bisa lebih cepat.','https://drive.google.com/open?id=5f81ba8280a4a5133d55078c5e38'),
  ('Tari Limpo','Supervisor Supply Chain Management','S1','Teknik Industri',6,'Pengalaman di UMKM lokal Maros selama beberapa tahun.','[{"skill": "Microsoft Excel", "level": 7}, {"skill": "Analisis Stok", "level": 8}, {"skill": "Negosiasi Vendor", "level": 9}, {"skill": "Manajemen Inventori", "level": 9}, {"skill": "Supply Chain", "level": 7}]','Domisili dalam Maros, tidak ada masalah jarak. Bersedia bekerja fleksibel.','https://drive.google.com/open?id=ff9cbcb541e21d9212f67f4d494f'),
  ('Zahra Wahid','Staff Accounting','D3','DKV',2,'Baru lulus, belum pernah bekerja formal.','[{"skill": "Ketelitian", "level": 6}, {"skill": "Laporan Keuangan", "level": 7}, {"skill": "Akuntansi Dasar", "level": 6}]','Perlu verifikasi lanjutan terkait pengalaman kerja sebelumnya.','https://drive.google.com/open?id=c211a34df8b37a667b315afb6b33'),
  ('Hasna Fauzi','Captain Store','SMA','IPS',4,'Pernah magang di perusahaan sejenis.','[{"skill": "Pelayanan Pelanggan", "level": 9}, {"skill": "Manajemen Stok", "level": 6}, {"skill": "Pengelolaan Kasir", "level": 7}]','Perlu tes kemampuan teknis lanjutan sebelum keputusan final.','https://drive.google.com/open?id=9204ce309444f6458ec17051b7b1'),
  ('Herlina Wahid','Staff Produksi','SMA','IPA',2,'Pengalaman di UMKM lokal Maros selama beberapa tahun.','[{"skill": "Ketelitian", "level": 5}, {"skill": "Kerja Tim", "level": 7}, {"skill": "Fisik Prima", "level": 8}, {"skill": "SOP Produksi", "level": 7}]','Sangat antusias. Motivasi tinggi untuk berkembang di perusahaan.','https://drive.google.com/open?id=f4f00c4764f08d9101894607b549'),
  ('Almira Salam','Captain Frontliner','SMA','Administrasi Perkantoran',3,'Fresh graduate dengan pengalaman magang 3-6 bulan.','[{"skill": "Kasir / POS System", "level": 6}, {"skill": "Manajemen Stok", "level": 7}, {"skill": "Komunikasi", "level": 6}, {"skill": "Leadership", "level": 6}, {"skill": "Pelayanan Pelanggan", "level": 7}]','Perlu tes kemampuan teknis lanjutan sebelum keputusan final.','https://drive.google.com/open?id=ee47681859154f54163683b1ff95'),
  ('Putri Ibrahim','Staff Accounting','D3','Administrasi Bisnis',1,'Pernah magang di perusahaan sejenis.','[{"skill": "Pembukuan", "level": 5}, {"skill": "Microsoft Excel", "level": 7}, {"skill": "Akuntansi Dasar", "level": 5}]','Menguasai tools yang dibutuhkan. Cocok untuk tim dinamis.','https://drive.google.com/open?id=f795dcad5d6c4c2eda92f4714702'),
  ('Ilham Harun','Captain Store','SMA','IPS',1,'Pengalaman di UMKM lokal Maros selama beberapa tahun.','[{"skill": "Pelayanan Pelanggan", "level": 7}, {"skill": "Pengelolaan Kasir", "level": 7}, {"skill": "Manajemen Stok", "level": 6}]','Perlu tes kemampuan teknis lanjutan sebelum keputusan final.','https://drive.google.com/open?id=4a14354d887875af0eee4b1fc024'),
  ('Tasrif Saputra','Staff Frontliner','SMA','IPA',2,'Pengalaman di UMKM lokal Maros selama beberapa tahun.','[{"skill": "Kasir / POS System", "level": 8}, {"skill": "Pelayanan Pelanggan", "level": 8}, {"skill": "Komunikasi", "level": 6}, {"skill": "Kerja Tim", "level": 7}]','Sudah pernah kerja di industri serupa. Onboarding bisa lebih cepat.','https://drive.google.com/open?id=4218dccee1173ef8052059640932'),
  ('Umar Umar','Staff HRD','S1','Psikologi',1,'Memiliki pengalaman di industri yang berkaitan.','[{"skill": "HRIS", "level": 6}, {"skill": "Komunikasi", "level": 5}, {"skill": "Administrasi HR", "level": 6}]','Perlu verifikasi lanjutan terkait pengalaman kerja sebelumnya.','https://drive.google.com/open?id=f9602bb0feb655111b1d7ad0d151'),
  ('Zubaidah Hamzah','Staff Frontliner','SMK','Tata Boga',2,'Pengalaman di UMKM lokal Maros selama beberapa tahun.','[{"skill": "Pelayanan Pelanggan", "level": 5}, {"skill": "Kasir / POS System", "level": 8}, {"skill": "Kerja Tim", "level": 6}]','Kandidat potensial, attitude baik dan komunikatif. Direkomendasikan untuk tahap berikutnya.','https://drive.google.com/open?id=9d985fd06da1096375c020b1317a'),
  ('Dimas Jaya Bahri','Staff Frontliner','SMA','IPA',1,'Pernah magang di perusahaan sejenis.','[{"skill": "Ketelitian", "level": 5}, {"skill": "Pelayanan Pelanggan", "level": 7}, {"skill": "Komunikasi", "level": 6}, {"skill": "Kasir / POS System", "level": 5}, {"skill": "Kerja Tim", "level": 5}]','Menguasai tools yang dibutuhkan. Cocok untuk tim dinamis.','https://drive.google.com/open?id=3f475574d2e922471709af645be0'),
  ('Tari Verdi','Staff Produksi','SMA','IPS',0,'Fresh graduate dengan pengalaman magang 3-6 bulan.','[{"skill": "SOP Produksi", "level": 5}, {"skill": "Kebersihan Produksi", "level": 6}, {"skill": "Kerja Tim", "level": 6}, {"skill": "Fisik Prima", "level": 5}]','Menguasai tools yang dibutuhkan. Cocok untuk tim dinamis.','https://drive.google.com/open?id=b5476778ac45978116d5cce93f61'),
  ('Rahmat Dg. Natsir','Staff Frontliner (Shift Malam)','SMA','IPS',1,'Pernah magang di perusahaan sejenis.','[{"skill": "Komunikasi", "level": 4}, {"skill": "Kasir / POS System", "level": 5}, {"skill": "Ketahanan Fisik", "level": 4}, {"skill": "Pelayanan Pelanggan", "level": 6}]','Sudah pernah kerja di industri serupa. Onboarding bisa lebih cepat.','https://drive.google.com/open?id=1401eb8d5df4a862b064f052f4c1'),
  ('Hasna Talib','Office Boy','SMA','Administrasi Perkantoran',3,'Baru lulus, belum pernah bekerja formal.','[{"skill": "Pengiriman Dokumen", "level": 7}, {"skill": "Disiplin", "level": 7}, {"skill": "Kebersihan & Kerapian", "level": 7}, {"skill": "Tanggung Jawab", "level": 7}]','Menguasai tools yang dibutuhkan. Cocok untuk tim dinamis.','https://drive.google.com/open?id=abecc8070004db30c413998dad5e'),
  ('Azizah Arfah','Teknisi','SMK','Tata Niaga',5,'Pernah kerja part-time di bidang terkait.','[{"skill": "Perawatan Mesin", "level": 8}, {"skill": "Kelistrikan", "level": 8}, {"skill": "Mekanik", "level": 9}]','Dokumen tidak lengkap saat pengumpulan berkas. Perlu dilengkapi.','https://drive.google.com/open?id=142504cbd08a5465e394ab68024d'),
  ('Azizah Jaya','Staff Produksi','SMA','Administrasi Perkantoran',1,'Pernah bekerja di bidang yang relevan sebelumnya.','[{"skill": "SOP Produksi", "level": 4}, {"skill": "Ketelitian", "level": 7}, {"skill": "Kebersihan Produksi", "level": 5}, {"skill": "Kerja Tim", "level": 4}]','Sangat antusias. Motivasi tinggi untuk berkembang di perusahaan.','https://drive.google.com/open?id=b4962050d988584b67f93612943e'),
  ('Erna Maulana','Staff HRD','D3','Akuntansi',3,'Pengalaman di UMKM lokal Maros selama beberapa tahun.','[{"skill": "Microsoft Excel", "level": 9}, {"skill": "Rekrutmen", "level": 8}, {"skill": "HRIS", "level": 6}, {"skill": "Administrasi HR", "level": 8}, {"skill": "Komunikasi", "level": 6}]','Perlu tes kemampuan teknis lanjutan sebelum keputusan final.','https://drive.google.com/open?id=aded3394eff649d6b3d93079114f')
) AS v(nama,posisi,pendidikan,jurusan,exp_thn,exp_desc,skills,catatan_hr,cv_url)
  ON r.nama = v.nama AND r.posisi = v.posisi
ON CONFLICT (recruitment_id) DO NOTHING;


-- ── PART C: UPDATE cv_url semua candidate_skills yang masih NULL ──
UPDATE candidate_skills cs
SET    cv_url = CONCAT(
         'https://drive.google.com/open?id=',
         SUBSTR(MD5(r.nama || r.posisi || cs.id::TEXT), 1, 28)
       ),
       updated_at = NOW()
FROM   recruitment r
WHERE  cs.recruitment_id = r.id
  AND  cs.cv_url IS NULL;


-- ── Verifikasi ──────────────────────────────────────────────
-- SELECT COUNT(*) AS total_recruitment FROM recruitment;
-- SELECT COUNT(*) AS total_candidate_skills FROM candidate_skills;
-- SELECT COUNT(*) AS skills_null_cv FROM candidate_skills WHERE cv_url IS NULL;
-- SELECT r.posisi, COUNT(r.id) total, COUNT(cs.id) has_skill,
--        COUNT(r.id)-COUNT(cs.id) missing
-- FROM recruitment r
-- LEFT JOIN candidate_skills cs ON cs.recruitment_id = r.id
-- GROUP BY r.posisi ORDER BY missing DESC;